class AddClasses < ActiveRecord::Migration
  def change
  	ClassTa.create( number:  "1.00", name:  "Introduction to Computers and Engineering Problem Solving")
	ClassTa.create( number:  "1.000", name:  "Computer Programming for Scientific and Engineering Applications")
	ClassTa.create( number:  "1.007", name:  "EES-Lab: Engineering for Environment and Sustainability")
	ClassTa.create( number:  "1.010", name:  "Uncertainty in Engineering")
	ClassTa.create( number:  "1.011", name:  "Project Evaluation and Management")
	ClassTa.create( number:  "1.013", name:  "Senior Civil and Environmental Engineering Design")
	ClassTa.create( number:  "1.015J", name:  "Design of Electromechanical Robotic Systems")
	ClassTa.create( number:  "1.016", name:  "Design for Complex Environmental Issues: Building Solutions and Communicating Ideas")
	ClassTa.create( number:  "1.018AJ", name:  "Fundamentals of Ecology I")
	ClassTa.create( number:  "1.018BJ", name:  "Fundamentals of Ecology II")
	ClassTa.create( number:  "1.020", name:  "Principles of Energy and Water Sustainability")
	ClassTa.create( number:  "2.00", name:  "Introduction to Design")
	ClassTa.create( number:  "2.001", name:  "Mechanics and Materials I")
	ClassTa.create( number:  "2.002", name:  "Mechanics and Materials II")
	ClassTa.create( number:  "2.003J", name:  "Dynamics and Control I")
	ClassTa.create( number:  "2.004", name:  "Dynamics and Control II")
	ClassTa.create( number:  "2.005", name:  "Thermal-Fluids Engineering I")
	ClassTa.create( number:  "2.006", name:  "Thermal-Fluids Engineering II")
	ClassTa.create( number:  "2.007", name:  "Design and Manufacturing I")
	ClassTa.create( number:  "2.008", name:  "Design and Manufacturing II")
	ClassTa.create( number:  "2.009", name:  "The Product Engineering Process")
	ClassTa.create( number:  "2.00AJ", name:  "Fundamentals of Engineering Design: Explore Space, Sea and Earth")
	ClassTa.create( number:  "2.00B", name:  "Toy Product Design")
	ClassTa.create( number:  "2.01", name:  "Elements of Structures")
	ClassTa.create( number:  "2.013", name:  "Engineering Systems Design")
	ClassTa.create( number:  "2.014", name:  "Engineering Systems Development")
	ClassTa.create( number:  "2.016", name:  "Hydrodynamics")
	ClassTa.create( number:  "2.017J", name:  "Design of Electromechanical Robotic Systems")
	ClassTa.create( number:  "2.019", name:  "Design of Ocean Systems")
	ClassTa.create( number:  "2.02A", name:  "Engineering Materials: Properties and Applications")
	ClassTa.create( number:  "2.02B", name:  "Mechanics of Structures")
	ClassTa.create( number:  "2.03", name:  "Dynamics I")
	ClassTa.create( number:  "2.031", name:  "Dynamics II")
	ClassTa.create( number:  "2.04A", name:  "Systems and Controls")
	ClassTa.create( number:  "2.04B", name:  "Introduction to Mechanical Vibration")
	ClassTa.create( number:  "2.05", name:  "Thermodynamics")  
  	ClassTa.create( number:  "3.003", name:   "Principles of Engineering Practice")
	ClassTa.create( number:  "3.004", name:   "Principles of Engineering Practice")
	ClassTa.create( number:  "3.012", name:   "Fundamentals of Materials Science and Engineering")
	ClassTa.create( number:  "3.014", name:   "Materials Laboratory")
	ClassTa.create( number:  "3.016", name:   "Mathematical Methods for Materials Scientists and Engineers")
	ClassTa.create( number:  "3.021", name:   "Introduction to Modeling and Simulation")
	ClassTa.create( number:  "3.022", name:   "Microstructural Evolution in Materials")
	ClassTa.create( number:  "3.024", name:   "Electronic, Optical and Magnetic Properties of Materials")
	ClassTa.create( number:  "3.032", name:   "Mechanical Behavior of Materials")
	ClassTa.create( number:  "3.034", name:   "Organic and Biomaterials Chemistry")
	ClassTa.create( number:  "3.035", name:   "Problems in Materials Science and Engineering")
	ClassTa.create( number:  "3.036", name:   "Problems in Materials Science and Engineering")
	ClassTa.create( number:  "3.036", name:  "Problems in Materials Science and Engineering")
	ClassTa.create( number:  "3.038", name:   "Problems in Materials Science and Engineering")
	ClassTa.create( number:  "3.039", name:   "Problems in Materials Science and Engineering")
	ClassTa.create( number:  "3.038", name:  "Problems in Materials Science and Engineering")
	ClassTa.create( number:  "3.042", name:   "Materials Project Laboratory")
	ClassTa.create( number:  "3.044", name:   "Materials Processing")
	ClassTa.create( number:  "3.046", name:   "Thermodynamics of Materials")
	ClassTa.create( number:  "3.048", name:   "Advanced Materials Processing")
	ClassTa.create( number:  "3.052", name:   "Nanomechanics of Materials and Biomaterials")
	ClassTa.create( number:  "3.053J", name:   "Molecular, Cellular, and Tissue Biomechanics")
	ClassTa.create( number:  "3.054", name:   "Cellular Solids: Structure, Properties, Applications")
	ClassTa.create( number:  "3.055J", name:   "Biomaterials Science and Engineering")
	ClassTa.create( number:  "3.063", name:   "Polymer Physics")
	ClassTa.create( number:  "3.064", name:   "Polymer Engineering")
	ClassTa.create( number:  "3.07", name:   "Introduction to Ceramics")
	ClassTa.create( number:  "3.072", name:   "Symmetry, Structure and Tensor Properties of Materials")
	ClassTa.create( number:  "3.074", name:   "Imaging of Materials")
	ClassTa.create( number:  "3.080", name:   "Economic and Environmental Materials Selection")
	ClassTa.create( number:  "3.081", name:   "Industrial Ecology of Materials")
	ClassTa.create( number:  "3.086", name:   "Innovation and Commercialization of Materials Technology")
	ClassTa.create( number:  "3.091", name:   "Introduction to Solid-State Chemistry")
	ClassTa.create(number:  "5.03", name:  "Principles of Inorganic Chemistry I")
	ClassTa.create(number:  "5.04", name:  "Principles of Inorganic Chemistry II")
	ClassTa.create(number:  "5.07J", name:  "Biological Chemistry I")
	ClassTa.create(number:  "5.08J", name:  "Biological Chemistry II")
	ClassTa.create(number:  "5.111", name:  "Principles of Chemical Science")
	ClassTa.create(number:  "5.112", name:  "Principles of Chemical Science")
	ClassTa.create(number:  "5.12", name:  "Organic Chemistry I")
	ClassTa.create(number:  "5.13", name:  "Organic Chemistry II")
	ClassTa.create( number:  "6.002", name:   "Circuits and Electronics")
	ClassTa.create( number:  "6.003", name:   "Signals and Systems")
	ClassTa.create( number:  "6.004", name:   "Computation Structures")
	ClassTa.create( number:  "6.005", name:   "Elements of Software Construction")
	ClassTa.create( number:  "6.006", name:   "Introduction to Algorithms")
	ClassTa.create( number:  "6.007", name:   "Electromagnetic Energy: From Motors to Solar Cells")
	ClassTa.create( number:  "6.008", name:   "Introduction to Inference")
	ClassTa.create( number:  "6.01", name:   "Introduction to EECS I")
	ClassTa.create( number:  "6.011", name:   "Introduction to Communication, Control, and Signal Processing")
	ClassTa.create( number:  "6.012", name:   "Microelectronic Devices and Circuits")
	ClassTa.create( number:  "6.013", name:   "Electromagnetics and Applications")
	ClassTa.create( number:  "6.02", name:   "Introduction to EECS II")
	ClassTa.create( number:  "6.021J", name:   "Cellular Biophysics and Neurophysiology")
	ClassTa.create( number:  "6.022J", name:   "Quantitative Systems Physiology")
	ClassTa.create( number:  "6.023J", name:   "Fields, Forces and Flows in Biological Systems")
	ClassTa.create( number:  "6.024J", name:   "Molecular, Cellular, and Tissue Biomechanics")
	ClassTa.create( number:  "6.025J", name:   "Medical Device Design")
	ClassTa.create( number:  "6.033", name:   "Computer System Engineering")
	ClassTa.create( number:  "6.034", name:   "Artificial Intelligence")
	ClassTa.create( number:  "6.035", name:   "Computer Language Engineering")
	ClassTa.create( number:  "6.036", name:   "Introduction to Machine Learning")
	ClassTa.create( number:  "6.041", name:   "Probabilistic Systems Analysis")
	ClassTa.create( number:  "6.042J", name:   "Mathematics for Computer Science")
	ClassTa.create( number:  "6.045J", name:   "Automata, Computability, and Complexity")
	ClassTa.create( number:  "6.046J", name:   "Design and Analysis of Algorithms")
	ClassTa.create( number:  "6.141J", name:   "Robotics: Science and Systems I")
	ClassTa.create( number:  "6.142J", name:   "Robotics: Science and Systems II")
	ClassTa.create( number:  "6.170", name:   "Software Studio")
	ClassTa.create( number:  "6.803", name:   "The Human Intelligence Enterprise")
	ClassTa.create( number:  "6.804J", name:   "Computational Cognitive Science")
	ClassTa.create( number:  "6.805J", name:   "Foundations of Information Policy")
	ClassTa.create( number:  "6.811", name:   "Principles and Practice of Assistive Technology")
	ClassTa.create( number:  "6.813", name:   "User Interface Design and Implementation")
	ClassTa.create( number:  "6.814", name:   "Database Systems")
  	ClassTa.create( number:  "7.012", name:   "Introductory Biology")
	ClassTa.create( number:  "7.013", name:   "Introductory Biology")
	ClassTa.create( number:  "7.014", name:   "Introductory Biology")
	ClassTa.create( number:  "7.015", name:   "Introductory Biology")
	ClassTa.create( number:  "7.016", name:   "Introductory Biology")
	ClassTa.create( number:  "7.03", name:   "Genetics")
	ClassTa.create( number:  "7.05", name:   "General Biochemistry")
	ClassTa.create( number:  "7.06", name:   "Cell Biology")
  	ClassTa.create( number:  "8.01", name:   "Physics I")
	ClassTa.create( number:  "8.011", name:   "Physics I")
	ClassTa.create( number:  "8.012", name:   "Physics I")
	ClassTa.create( number:  "8.01L", name:   "Physics I")
	ClassTa.create( number:  "8.02", name:   "Physics II")
	ClassTa.create( number:  "9.00", name:   "Introduction to Psychological Science")
	ClassTa.create( number:  "9.01", name:   "Introduction to Neuroscience")
	ClassTa.create( number:  "9.04", name:   "Sensory Systems")
	ClassTa.create( number:  "9.07", name:   "Statistics for Brain and Cognitive Science")
	ClassTa.create( number:  "9.09", name:  " Cellular and Molecular Neurobiology")
	ClassTa.create( number:  "9.10", name:   "Cognitive Neuroscience")
	ClassTa.create( number:  "9.12", name:   "Experimental Molecular Neurobiology")
	ClassTa.create( number:  "9.14", name:   "Brain Structure and its Origins")
	ClassTa.create( number:  "14.01", name:   "Principles of Microeconomics")
	ClassTa.create( number:  "14.02", name:   "Principles of Macroeconomics")
	ClassTa.create( number:  "14.03", name:   "Microeconomic Theory and Public Policy")
	ClassTa.create( number:  "14.04", name:   "Intermediate Microeconomic Theory")
	ClassTa.create( number:  "14.05", name:   "Intermediate Macroeconomics")
	ClassTa.create( number:  "14.08", name:   "Technical Topics in Economics")
	ClassTa.create( number:  "14.11", name:   "Topics in Economics")
	ClassTa.create( number:  "14.12", name:   "Economic Applications of Game Theory")
	ClassTa.create( number:  "14.15", name:  " Networks")
	ClassTa.create( number:  "14.16", name:   "Strategy and Information")
	ClassTa.create( number:  "14.19", name:   "Market Design")
	ClassTa.create( number: "16.001", name:  "Unified Engineering I")
	ClassTa.create( number: "16.002", name:  "Unified Engineering II")
	ClassTa.create( number: "16.003", name:  "Unified Engineering III")
	ClassTa.create( number: "16.004", name:  "Unified Engineering IV")
	ClassTa.create( number: "16.06 ", name: "rinciples of Automatic Control")
	ClassTa.create(number:  "16.07", name:   "Dynamics")
	ClassTa.create(number:  "16.09", name:   "Statistics and Probability")
	ClassTa.create(number:  "16.10", name:  " Aerodynamics")
	ClassTa.create(number:  "16.20", name:   "Structural Mechanics")
	ClassTa.create(number:  "16.30", name:   "Feedback Control Systems")
	ClassTa.create(number: "18.01 ", name:  "Calculus")
	ClassTa.create(number: "18.014", name:   "Calculus with Theory")
	ClassTa.create(number: "18.01A", name:   "Calculus")
	ClassTa.create(number: "18.02 ", name:  "Calculus")
	ClassTa.create(number: "18.022", name:   "Calculus")
	ClassTa.create(number: "18.024", name:   "Calculus with Theory")
	ClassTa.create(number: "18.02A", name:   "Calculus")
	ClassTa.create(number: "18.03 ", name:  "Differential Equations")
	ClassTa.create(number: "18.034", name:   "Differential Equations")
	ClassTa.create(number: "18.04 ", name:  "Complex Variables with Applications")
	ClassTa.create(number: "18.05 ", name:  "Introduction to Probability and Statistics")
	ClassTa.create(number: "18.06 ", name:  "Linear Algebra")
	ClassTa.create(number: "18.062", name:  "Mathematics for Computer Science")
	ClassTa.create(number: "18.104", name:   "Seminar in Analysis")




  end
end
